spring:
  datasource:
    url: jdbc:mysql://attendance-mysql.mysql.database.azure.com:3306/attendance_db?useSSL=true&requireSSL=true
    username: adminuser
    password: Sairam@Azure123  # <-- update with your actual password here
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  address: 0.0.0.0
  port: 8080
