spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db
    username: root
    password: Sairam9494@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
